# Generated by Django 3.1.2 on 2020-10-16 10:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IslandingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=20, verbose_name='Method')),
                ('island_imbalance', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=3)),
                ('total_imbalance', models.FloatField(blank=True, null=True)),
                ('island_imbalance_after_cut', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=3)),
                ('total_imbalace_after_cut', models.FloatField(blank=True, null=True)),
                ('lines_to_cut', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grid', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
