# Generated by Django 3.1.2 on 2020-10-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islanding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islandingscheme',
            old_name='total_imbalace_after_cut',
            new_name='total_imbalance_after_cut',
        ),
    ]
