# Generated by Django 3.1.5 on 2021-01-18 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islanding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islandingscheme',
            name='island_imbalance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='islandingscheme',
            name='island_imbalance_after_cut',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=3),
        ),
    ]
