# Generated by Django 3.2.7 on 2021-10-07 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islanding', '0002_auto_20210118_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islandingscheme',
            name='island_imbalance_after_cut',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=None),
        ),
    ]
