# Generated by Django 3.1.2 on 2020-10-22 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islanding', '0002_auto_20201022_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islandingscheme',
            name='island_imbalance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='islandingscheme',
            name='island_imbalance_after_cut',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=3),
        ),
    ]
